/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.3.1/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    val kotlinVersion = providers.gradleProperty("versions.kotlin").get()
    plugins {
        id("org.jetbrains.kotlin.jvm") version kotlinVersion
        // PROBE — openspec/changes/probe-kotlin-emitter, for :codegen-kotlin only.
        id("org.jetbrains.kotlin.plugin.serialization") version kotlinVersion
    }
}

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "kdaisyui"

include("lib")
include("ktor-integration")
include("example-app")
include("e2e-tests")

// PROBE — openspec/changes/probe-kotlin-emitter. Remove this line and the directory
// to discard the experiment.
include("codegen-kotlin")
