/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.3.1/userguide/multi_project_builds.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    // `pluginManagement` runs before the version catalog (`libs`) exists, so the
    // type-safe `libs.*` accessors are not available here. Read the Kotlin version
    // directly from the catalog TOML to keep libs.versions.toml the single source
    // of truth. The `[versions] kotlin = "x.y.z"` line is matched with a minimal,
    // dependency-free parser (JDK only).
    val catalog = file("gradle/libs.versions.toml").readLines()
    val kotlinVersion = catalog
        .firstNotNullOfOrNull { line ->
            Regex("""^\s*kotlin\s*=\s*"([^"]+)"\s*$""").find(line)?.groupValues?.get(1)
        }
        ?: error("Could not find `kotlin` version in gradle/libs.versions.toml")
    plugins {
        id("org.jetbrains.kotlin.jvm") version kotlinVersion
    }
}

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "kdaisyui"

include("lib")
include("ktor-integration")
include("example-app")
include("e2e-tests")
