/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/9.3.1/userguide/building_java_projects.html in the Gradle documentation.
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("kdaisyui.kotlin-library-conventions")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

sourceSets {
    main {
        kotlin.srcDir("build/generated/sources/kdaisyui")
    }
}

dependencies {
    api("org.jetbrains.kotlinx:kotlinx-html-jvm:${project.property("versions.kotlinx-html")}")

    implementation("org.webjars:webjars-locator-core:${project.property("versions.webjar-locator-core")}")
    implementation("org.webjars.npm:daisyui:${project.property("versions.webjar.daisyui")}")
}

tasks.named("compileKotlin") {
    dependsOn(":codegen:generateComponents")
}

tasks.named("compileTestKotlin") {
    dependsOn(":codegen:generateComponents")
}

testing {
    suites {
        // Configure the built-in test suite
        val test by getting(JvmTestSuite::class) {
            // Use Kotlin Test test framework
            useKotlinTest(project.property("versions.kotlin").toString())
        }
    }
}
