component: Card
functions:
  - name: daisyCard
    cssClass: card
    htmlElement: DIV
  - name: daisyCardBody
    cssClass: card-body
    htmlElement: DIV
  - name: daisyCardTitle
    cssClass: card-title
    htmlElement: H2
    textParam: true
