component: Checkbox
htmlElement: INPUT
fixedInputType: checkBox
noContent: true
extras:
  - name: checked
    type: "Boolean"
    default: "false"
    apply: "if (checked) this.checked = true"
  - name: disabled
    type: "Boolean"
    default: "false"
    apply: "if (disabled) this.disabled = true"
