component: Drawer
functions:
  - name: daisyDrawer
    cssClass: drawer
    htmlElement: DIV
    htmlTag: div
    extras:
      - name: drawerId
        type: "String"
        default: '"my-drawer"'
        imports:
          - "kotlinx.html.InputType"
        apply: |
          input {
              this.id = drawerId
              type = InputType.checkBox
              addClassNames("drawer-toggle")
          }
  - name: daisyDrawerContent
    cssClass: drawer-content
    htmlElement: DIV
    htmlTag: div
  - name: daisyDrawerSide
    cssClass: drawer-side
    htmlElement: DIV
    htmlTag: div
  - name: daisyDrawerOverlay
    cssClass: drawer-overlay
    htmlElement: LABEL
    htmlTag: label
    noContent: true
    extras:
      - name: drawerId
        type: "String"
        default: '"my-drawer"'
        imports: []
        apply: 'attributes["for"] = drawerId'
        position: before_classes
  - name: daisyDrawerButton
    cssClass: drawer-button
    htmlElement: LABEL
    htmlTag: label
    textParam: true
    extras:
      - name: drawerId
        type: "String"
        default: '"my-drawer"'
        imports: []
        apply: 'attributes["for"] = drawerId'
        position: before_classes
