component: Dropdown
functions:
  - name: daisyDropdown
    cssClass: dropdown
    htmlElement: DIV
  - name: daisyDropdownContent
    cssClass: dropdown-content
    baseClasses:
      - "menu"
      - "dropdown-content"
    htmlElement: UL
