component: Fieldset
functions:
  - name: daisyFieldset
    cssClass: fieldset
    htmlElement: FIELDSET
  - name: daisyFieldsetLegend
    cssClass: fieldset-legend
    receiver: FIELDSET
    htmlElement: LEGEND
    textParam: true
  - name: daisyFieldsetLabel
    cssClass: fieldset-label
    receiver: FIELDSET
    htmlElement: SPAN
    textParam: true
