component: Label
functions:
  - name: daisyLabel
    cssClass: label
    htmlElement: LABEL
    textParam: true
  - name: daisyLabelText
    cssClass: label-text
    htmlElement: SPAN
    textOnly: true
