component: Radio
htmlElement: INPUT
fixedInputType: radio
noContent: true
extras:
  - name: name
    type: "String?"
    default: "null"
    apply: "if (name != null) this.name = name"
  - name: checked
    type: "Boolean"
    default: "false"
    apply: "if (checked) this.checked = true"
  - name: disabled
    type: "Boolean"
    default: "false"
    apply: "if (disabled) this.disabled = true"
