component: Range
htmlElement: INPUT
fixedInputType: range
noContent: true
extras:
  - name: min
    type: "String?"
    default: "null"
    apply: "if (min != null) this.min = min"
  - name: max
    type: "String?"
    default: "null"
    apply: "if (max != null) this.max = max"
  - name: value
    type: "String?"
    default: "null"
    apply: "if (value != null) this.value = value"
  - name: step
    type: "String?"
    default: "null"
    apply: "if (step != null) this.step = step"
  - name: disabled
    type: "Boolean"
    default: "false"
    apply: "if (disabled) this.disabled = true"
